SOURCE = ..

include $(SOURCE)/Rules.mk

DOCS = \
	ASTExtensions.html \
	index.html \
	jif_demos.html \
	jif_programming.html \
	jif_runtime.html \
	jif_usage.html \
	TypeSystemExtensions.html \

release:
	mkdir -p $(REL_DOC)
	cp -f $(DOCS) $(REL_DOC)

