
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Thu Nov 29 14:47:08 EST 2001
//----------------------------------------------------

package jltools.util.jlgen.parse;

/** CUP generated class containing symbol constants. */
public class Constant {
  /* terminals */
  public static final int WITH = 27;
  public static final int PARSER = 23;
  public static final int SEMI = 9;
  public static final int INIT = 25;
  public static final int STAR = 29;
  public static final int BAR = 12;
  public static final int SCAN = 26;
  public static final int COMMA = 8;
  public static final int NON = 24;
  public static final int CODE = 21;
  public static final int ID = 35;
  public static final int DOT = 16;
  public static final int LEFT = 31;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int TRANSFER = 5;
  public static final int INCLUDE = 2;
  public static final int START = 28;
  public static final int NONTERMINAL = 14;
  public static final int ACTION = 22;
  public static final int LBRACK = 17;
  public static final int IMPORT = 20;
  public static final int COLON = 10;
  public static final int LBRACE = 6;
  public static final int CODE_STR = 36;
  public static final int RBRACK = 18;
  public static final int TO = 3;
  public static final int PACKAGE = 19;
  public static final int NONASSOC = 33;
  public static final int DROP = 4;
  public static final int RBRACE = 7;
  public static final int PRECEDENCE = 30;
  public static final int EXTEND = 37;
  public static final int OVERRIDE = 38;
  public static final int PERCENT_PREC = 15;
  public static final int TERMINAL = 13;
  public static final int RIGHT = 32;
  public static final int STRING_CONST = 34;
  public static final int COLON_COLON_EQUALS = 11;
}

