terminal COMPARISON_OPERATOR;
terminal NAME;
terminal STRING;
terminal INTNUM;
terminal FLOATNUM;
terminal ADD;
terminal COLUMN;
terminal EQUAL;
terminal SELECT, FROM, WHERE;
terminal DELETE;
terminal INSERT, INTO, VALUES;
terminal UPDATE, SET;
terminal AND;
terminal OR;
terminal NOT;
terminal ALTER, TTABLE;
terminal CREATE;
terminal DROP;
terminal NULL_VALUE;
terminal VARCHAR;
terminal INT;
terminal INTEGER;
terminal DOUBLE;
terminal PRECISION;
terminal DATE;
terminal ORDER, BY;
terminal IS;

terminal LPAREN, RPAREN, COMMA, TIMES, MINUS, PLUS, DIV;

non terminal y_sql, y_alter, y_create, y_drop, y_select, y_delete, y_insert,
y_update, y_columndefs, y_columndef, y_columns, y_column_list, y_table,
y_values, y_value_list, y_assignments, y_assignment, y_condition,
y_sub_condition, y_sub_condition2, y_boolean, y_comparison, y_expression,
y_product, y_term, y_atom, y_value, y_column, y_order;

start with y_sql;

y_sql::=	
		y_alter
	|	y_create
	|	y_drop
	|	y_insert
	|	y_select
	|	y_update
	|	y_delete
	;
	
y_alter::=
		ALTER TTABLE y_table ADD COLUMN y_columndef	
	|	ALTER TTABLE y_table ADD y_columndef		
	;
	
y_create::=
		CREATE TTABLE y_table LPAREN y_columndefs RPAREN	
	;
	
y_drop::=
		DROP TTABLE y_table				
	;

y_select::=
		SELECT y_columns FROM y_table			
	|	SELECT y_columns FROM y_table WHERE y_condition	
	|	SELECT y_columns FROM y_table ORDER BY y_order	
	|	SELECT y_columns FROM y_table WHERE y_condition ORDER BY y_order 
	;
	
y_delete::=
		DELETE FROM y_table				
        |	DELETE FROM y_table WHERE y_condition		
	;

y_insert::=
		INSERT INTO y_table y_values			
        |	INSERT INTO y_table LPAREN y_columns RPAREN y_values	
	;

y_update::=
		UPDATE y_table SET y_assignments		
	|	UPDATE y_table SET y_assignments WHERE y_condition	

	;
	
y_columndefs::=
		y_columndef
	|	y_columndefs COMMA y_columndef
	;

y_columndef::=
		NAME VARCHAR LPAREN INTNUM RPAREN	
	|	NAME INT 			
	|	NAME INTEGER 			
	|	NAME DOUBLE			
	|	NAME DOUBLE PRECISION		
	|	NAME DATE			
	;

y_columns::=
	TIMES
        |	y_column_list
	;
	
y_column_list::=
		NAME				
	|	y_column_list COMMA NAME		
	;

y_table::=
		NAME 				
	;
	
y_values::=
		VALUES LPAREN y_value_list RPAREN
	;

y_value_list::=
		NULL_VALUE			
	|	STRING				
        |	INTNUM				
        |      MINUS INTNUM 			
	|	FLOATNUM			
	| 	MINUS FLOATNUM 			
	|	y_value_list COMMA NULL_VALUE	
	|	y_value_list COMMA STRING		
	|	y_value_list COMMA INTNUM		
	| 	y_value_list COMMA MINUS INTNUM 	
	|	y_value_list COMMA FLOATNUM	
	| 	y_value_list COMMA MINUS FLOATNUM 	
	;

y_assignments::=
		y_assignment
	|	y_assignments COMMA y_assignment
	;
	
y_assignment::=
                NAME EQUAL NULL_VALUE	
        |       NAME EQUAL y_expression 
	;

y_condition::=	
		y_sub_condition 	
	;

y_sub_condition::=	
		y_sub_condition2 
	|	y_sub_condition OR y_sub_condition2 
	;

y_sub_condition2::=	
		y_boolean 
	|	y_sub_condition2 AND y_boolean 
	;

y_boolean::=	
		y_comparison 
	|	LPAREN y_sub_condition RPAREN 
	|	NOT y_boolean 
	;


y_comparison::=
		y_expression EQUAL y_expression 
	|	y_expression COMPARISON_OPERATOR y_expression 
	|	y_expression IS NULL_VALUE 
	|	y_expression NOT NULL_VALUE 
	;	


y_expression::=
		y_product			
	|	y_expression PLUS y_product 
	|	y_expression MINUS y_product 
	;

y_product::=
		y_term				
	|	y_product TIMES y_term 
	|	y_product DIV y_term 
	;

y_term::=
		y_atom				
	|	MINUS y_term 
	;

y_atom::=
		y_value				
	|	y_column			
	|	LPAREN y_expression RPAREN		
	;

 
y_value::=
		STRING				
	|	INTNUM				
	|	FLOATNUM			
	;


y_column::=
		NAME				
	;

y_order::=
		NAME 				
	;
