//http://stackoverflow.com/questions/196179/shift-reduce-conflict
//(unamb)

terminal FOR;
terminal END;
terminal THINGS;
terminal WHILE;
terminal SET;
terminal IF;
terminal ELSEIF;
terminal ELSE;

terminal SHARP, LPAREN, RPAREN;

non terminal program, statements, stmt, flow, else, elseifs;

start with program;

program ::= statements
        ;

statements ::= /*empty */
           | statements stmt
           ;

stmt ::= flow
     | THINGS
     ;

flow ::= SHARP IF LPAREN RPAREN statements else
     ;

else ::= SHARP END
     | SHARP ELSE statements SHARP END
     | elseifs
     ;

elseifs ::= elseifs SHARP ELSEIF statements else
        | SHARP ELSEIF statements else
        ;
